<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\erp.minepress.application\erp.minepress.application.csproj" />
    <ProjectReference Include="..\erp.minepress.persistence\erp.minepress.persistence.csproj" />
    <ProjectReference Include="..\erp.minepress.infrastructure\erp.minepress.infrastructure.csproj" />
    <ProjectReference Include="..\erp.minepress.frameworks\erp.minepress.frameworks.csproj" />
    <ProjectReference Include="..\erp.minepress.notification\erp.minepress.notification.csproj" />
    <ProjectReference Include="..\erp.minepress.tenants\erp.minepress.tenants.csproj" />
    <ProjectReference Include="..\erp.minepress.printingcostingengine\erp.minepress.printingcostingengine.csproj" />
    <ProjectReference Include="..\erp.minepress.agentic.ai\erp.minepress.agentic.ai.csproj" />
  </ItemGroup>

</Project>
