using System;
using System.Collections.Generic;

namespace erp.minepress.persistence.Models;

/// <summary>
/// General journal voucher header. Supports manual entries, auto-generated GL postings from invoices/payments, and reversing entries. Debit must equal Credit.
/// </summary>
public partial class TrnJournalVoucher
{
    public long JournalId { get; set; }

    public string JournalNo { get; set; } = null!;

    public DateOnly JournalDate { get; set; }

    /// <summary>
    /// GENERAL, OPENING, CLOSING, ADJUSTMENT, DEPRECIATION, PROVISION, REVERSAL, AUTO
    /// </summary>
    public string JournalType { get; set; } = null!;

    public int CompanyId { get; set; }

    public int? LocationId { get; set; }

    public int? FinYearId { get; set; }

    public string? ReferenceNo { get; set; }

    public DateOnly? ReferenceDate { get; set; }

    public decimal? TotalDebit { get; set; }

    public decimal? TotalCredit { get; set; }

    public string? Narration { get; set; }

    public string Status { get; set; } = null!;

    public bool? IsAutoGenerated { get; set; }

    public string? SourceVoucherType { get; set; }

    public long? SourceVoucherId { get; set; }

    public string? SourceVoucherNo { get; set; }

    public bool? IsReversingEntry { get; set; }

    public long? OriginalJournalId { get; set; }

    public DateOnly? ReversalDate { get; set; }

    public bool? IsCancelled { get; set; }

    public long? CancelledBy { get; set; }

    public DateTime? CancelledOn { get; set; }

    public string? CancelReason { get; set; }

    public bool? IsPosted { get; set; }

    public DateTime? PostedOn { get; set; }

    public long? PostedBy { get; set; }

    public long CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual MstCompany Company { get; set; } = null!;

    public virtual ICollection<TrnJournalVoucher> InverseOriginalJournal { get; set; } = new List<TrnJournalVoucher>();

    public virtual TrnJournalVoucher? OriginalJournal { get; set; }

    public virtual ICollection<TrnJournalVoucherLine> TrnJournalVoucherLines { get; set; } = new List<TrnJournalVoucherLine>();
}
