-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS minepress_db.tenant_audit_logs
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    user_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    action character varying(100) COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    entity_id uuid,
    old_values jsonb,
    new_values jsonb,
    ip_address inet,
    user_agent character varying(500) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    additional_info character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tenant_audit_logs_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS minepress_db.tenant_audit_logs
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE minepress_db.tenant_audit_logs
    IS 'Comprehensive audit log for compliance (GDPR, HIPAA, SOC2)';

COMMENT ON COLUMN minepress_db.tenant_audit_logs.old_values
    IS 'Previous state before change (JSONB)';

COMMENT ON COLUMN minepress_db.tenant_audit_logs.new_values
    IS 'New state after change (JSONB)';

COMMENT ON COLUMN minepress_db.tenant_audit_logs.ip_address
    IS 'Client IP address (INET type for efficient storage)';

CREATE TABLE IF NOT EXISTS minepress_db.tenant_connections
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    connection_type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'primary'::character varying,
    encrypted_connection_string text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    priority integer NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    CONSTRAINT tenant_connections_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS minepress_db.tenant_connections
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE minepress_db.tenant_connections
    IS 'Multiple connection strings for high availability';

CREATE TABLE IF NOT EXISTS minepress_db.tenant_encryption_keys
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    encrypted_key character varying(500) COLLATE pg_catalog."default" NOT NULL,
    key_identifier character varying(500) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rotated_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT tenant_encryption_keys_pkey PRIMARY KEY (id),
    CONSTRAINT tenant_encryption_keys_key_identifier_key UNIQUE (key_identifier)
);

ALTER TABLE IF EXISTS minepress_db.tenant_encryption_keys
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE minepress_db.tenant_encryption_keys
    IS 'Encryption key management with rotation support';

CREATE TABLE IF NOT EXISTS minepress_db.tenant_features
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    tenant_key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    feature_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    configuration jsonb DEFAULT '{}'::jsonb,
    enabled_at timestamp with time zone,
    disabled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    created_by character varying(100) COLLATE pg_catalog."default",
    updated_by character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT tenant_features_pkey PRIMARY KEY (id),
    CONSTRAINT uq_tenant_features_tenant_feature UNIQUE (tenant_id, feature_name)
);

ALTER TABLE IF EXISTS minepress_db.tenant_features
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE minepress_db.tenant_features
    IS 'Feature flags and configurations per tenant';

CREATE TABLE IF NOT EXISTS minepress_db.tenant_users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    tenant_key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    encrypted_email character varying(500) COLLATE pg_catalog."default" NOT NULL,
    encrypted_full_name character varying(500) COLLATE pg_catalog."default",
    role character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'user'::character varying,
    is_active boolean NOT NULL DEFAULT true,
    last_login_at timestamp with time zone,
    failed_login_attempts integer NOT NULL DEFAULT 0,
    locked_until timestamp with time zone,
    permissions jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    created_by character varying(100) COLLATE pg_catalog."default",
    updated_by character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT tenant_users_pkey PRIMARY KEY (id),
    CONSTRAINT uq_tenant_users_tenant_user UNIQUE (tenant_id, user_id)
);

ALTER TABLE IF EXISTS minepress_db.tenant_users
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE minepress_db.tenant_users
    IS 'Tenant user mappings with encrypted PII data';

CREATE TABLE IF NOT EXISTS minepress_db.tenants
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    encrypted_connection_string text COLLATE pg_catalog."default" NOT NULL,
    schema_name character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT 'public'::character varying,
    is_active boolean NOT NULL DEFAULT true,
    subscription_plan character varying(50) COLLATE pg_catalog."default",
    subscription_expires_at timestamp with time zone,
    max_users integer NOT NULL DEFAULT 10,
    current_users integer NOT NULL DEFAULT 0,
    storage_limit_mb bigint NOT NULL DEFAULT 1024,
    current_storage_mb bigint NOT NULL DEFAULT 0,
    encrypted_admin_email character varying(500) COLLATE pg_catalog."default",
    encrypted_admin_phone character varying(500) COLLATE pg_catalog."default",
    encrypted_api_key character varying(500) COLLATE pg_catalog."default",
    metadata jsonb DEFAULT '{}'::jsonb,
    ip_whitelist text[] COLLATE pg_catalog."default",
    enable_ip_restriction boolean NOT NULL DEFAULT false,
    require_two_factor boolean NOT NULL DEFAULT false,
    data_retention_days integer NOT NULL DEFAULT 365,
    last_activity_at timestamp with time zone,
    suspension_reason character varying(500) COLLATE pg_catalog."default",
    suspended_at timestamp with time zone,
    suspended_by character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    created_by character varying(100) COLLATE pg_catalog."default",
    updated_by character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT tenants_pkey PRIMARY KEY (id),
    CONSTRAINT tenants_tenant_key_key UNIQUE (tenant_key)
);

ALTER TABLE IF EXISTS minepress_db.tenants
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE minepress_db.tenants
    IS 'Master tenant configuration table with encrypted sensitive data (AES-256)';

COMMENT ON COLUMN minepress_db.tenants.encrypted_connection_string
    IS 'AES-256 encrypted database connection string';

COMMENT ON COLUMN minepress_db.tenants.encrypted_admin_email
    IS 'AES-256 encrypted administrator email address';

COMMENT ON COLUMN minepress_db.tenants.encrypted_admin_phone
    IS 'AES-256 encrypted administrator phone number';

COMMENT ON COLUMN minepress_db.tenants.encrypted_api_key
    IS 'AES-256 encrypted API key for programmatic access';

COMMENT ON COLUMN minepress_db.tenants.metadata
    IS 'Additional tenant metadata stored as JSONB';

COMMENT ON COLUMN minepress_db.tenants.ip_whitelist
    IS 'Array of whitelisted IP addresses/CIDR ranges';

ALTER TABLE IF EXISTS minepress_db.tenant_audit_logs
    ADD CONSTRAINT fk_tenant_audit_logs_tenant FOREIGN KEY (tenant_id)
    REFERENCES minepress_db.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS minepress_db.tenant_connections
    ADD CONSTRAINT fk_tenant_connections_tenant FOREIGN KEY (tenant_id)
    REFERENCES minepress_db.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tenant_connections_tenant
    ON minepress_db.tenant_connections(tenant_id);


ALTER TABLE IF EXISTS minepress_db.tenant_encryption_keys
    ADD CONSTRAINT fk_tenant_encryption_keys_tenant FOREIGN KEY (tenant_id)
    REFERENCES minepress_db.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_encryption_keys_tenant
    ON minepress_db.tenant_encryption_keys(tenant_id);


ALTER TABLE IF EXISTS minepress_db.tenant_features
    ADD CONSTRAINT fk_tenant_features_tenant FOREIGN KEY (tenant_id)
    REFERENCES minepress_db.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tenant_features_tenant
    ON minepress_db.tenant_features(tenant_id);


ALTER TABLE IF EXISTS minepress_db.tenant_users
    ADD CONSTRAINT fk_tenant_users_tenant FOREIGN KEY (tenant_id)
    REFERENCES minepress_db.tenants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tenant_users_tenant_id
    ON minepress_db.tenant_users(tenant_id);

END;